name: karaj
description: A new MTTWEREN application using flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.1.4
  get_storage: ^2.0.2
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  cloud_firestore: ^1.0.0
  google_maps_flutter: ^2.0.3
  firebase_messaging: ^9.1.3
  geolocator: ^7.0.3
  http: ^0.13.1
  flutter_polyline_points: ^1.0.0
  assets_audio_player: ^3.0.3+3
  geoflutterfire: ^3.0.0-nullsafety.2
  image_picker: ^0.7.4
  firebase_storage: ^8.0.5
  url_launcher: ^6.0.3
  simple_animations: ^3.1.1
  flare_flutter: ^3.0.0
  shimmer: ^2.0.0
  flutter_isolate: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  after_layout: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/sounds/
    - assets/flr/
  fonts:
    - family: "Cairo"
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo-Regular.ttf